version: 1.0-preview-1
steps:
  - build: -t {{.Run.Registry}}/public/azuremonitor/containerinsights/ciprod:{{.Run.Branch}}-{{.Run.Date}}-{{.Run.Commit | substr 0 7 }} .
    workingDirectory: kubernetes/linux
  - push: ["{{.Run.Registry}}/public/azuremonitor/containerinsights/ciprod:{{.Run.Branch}}-{{.Run.Date}}-{{.Run.Commit | substr 0 7 }}"]