apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerHealth-log-reader
rules:
  - apiGroups: ["", "metrics.k8s.io", "extensions", "apps"]
    resources:
      - "pods/log"
      - "events"
      - "nodes"
      - "pods"
      - "deployments"
      - "replicasets"
    verbs: ["get", "list"]
